config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)' do
    root 'store#index', as: 'store_index'
    resources :carts
    resources :line_items
    resources :orders
    resources :products
    resources :users
    resources :products do
      get :who_bought, on: :member
    end
    get 'admin' => 'admin#index'
    controller :sessions do
      get  'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, :image_url, :locale, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: /\.(gif|jpg|png)\Z/i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :locale, length: { is: 2 }

  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_line_items_empty

  private

  def ensure_line_items_empty
    return if line_items.empty?

    errors.add(:base, 'Line Items present')
    throw :abort
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.locale = I18n.locale

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.locale = I18n.locale
    respond_to do |format|
      if @product.update(product_params)
        @updated_product = @product
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        broadcast_products
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    return unless stale?(@latest_order)

    respond_to do |format|
      format.atom
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price)
  end

  def broadcast_products
    @products = Product.all
    ActionCable.server.broadcast 'products', html: render_to_string('store/index', layout: false)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %> <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.full_messages.each do |message| %> <li><%= message %></li>
        <% end %>
      </ul> </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, rows: 10, cols: 60 %>
  </div>
  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>
  <div class="actions"> <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', product_path(@product, locale: I18n.locale) %> |
<%= link_to 'Back', products_path(locale: I18n.locale) %>

app/views/products/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>
<h1>Products</h1>
<table>
  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to 'New product', new_product_path %>
      </td> </tr>
  </tfoot>
  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="image">
          <%= image_tag(product.image_url, class: 'list_image') %>
        </td>
        <td class="description"> <h1><%= product.title %></h1>
          <p>
            <%= truncate(strip_tags(product.description), length: 80) %>
          </p>
        </td>
        <td class="actions">
          <ul>
              <li><%= link_to 'Show', product_path(product, locale: I18n.locale) %></li>
              <li><%= link_to 'Edit', edit_product_path(product, locale: I18n.locale) %></li>
              <li>
                  <%= link_to 'Destroy', product, locale: I18n.locale, method: :delete, data: { confirm: 'Are you sure?' } %>
              </li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>
<p>
  <strong> title:</strong>
  <%= @product. title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @product.locale %>
</p>

<%= link_to 'Edit', edit_product_path(@product, locale: I18n.locale) %> |
<%= link_to 'Back', products_path(locale: I18n.locale) %>